apiVersion: v1
kind: Service
metadata:
  name: hello-node
  labels:
    app: hello-node
spec:
  selector:
    app: hello-node
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30003
  type: LoadBalancer
